services:
    semaphore_db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DB}
        volumes:
            - ${MYSQL_DATA:-./semaphore_mysql}:/var/lib/mysql   
        networks:
            - semaphore_network