services:
    server:
        volumes:
            - geoip:/geoip
    worker:
        volumes:
            - geoip:/geoip
    geoipupdate:
        image: "maxmindinc/geoipupdate:latest"
        volumes:
            - "${GEOIP_DATA:-./geoip}:/usr/share/GeoIP"
        env_file:
            - .env
        environment:
            GEOIPUPDATE_EDITION_IDS: "GeoLite2-City GeoLite2-ASN"
            GEOIPUPDATE_FREQUENCY: "8"
            GEOIPUPDATE_ACCOUNT_ID: ${GEOIP_ACCOUNT_ID}
            GEOIPUPDATE_LICENSE_KEY: ${GEOIP_LICENSE_KEY}
volumes:
    geoip:
        driver: local