---
- name: Installing packages for python env
  ansible.builtin.apt:
    name:
      - python3-pip
    update_cache: true
  become: true
  become_user: root
- name: Creates directory
  ansible.builtin.file:
    path: ./basic-http-server
    state: directory
    mode: '0755'
- name: Install apache2
  ansible.builtin.apt:
    name:
      - apache2
    update_cache: true
    # Enable this for uninstall
    # state: absent
  become: true
  become_user: root
