---
- name: Backup Vm Playbook
  hosts: all
  become: true
  remote_user: root
  tasks:
    - name: Backup all vms in the Proxmox cluster to storage mypbs
      community.general.proxmox_backup:
        api_user: "{{ api_user }}"
        api_password: "{{ api_secret }}"
        api_host: "{{ api_host }}"
        storage: "{{ backup_storage }}"
        mode: all
      vars:
        api_user: root@pam
        api_host: https://10.0.0.41:8006
        backup_storage: mypbs
        api_secret: a720e623-3fb7-48a5-97ae-74d4b653c197
