---
- name: Backup Vm Playbook
  hosts: all
  become: true
  remote_user: root
  roles:
    - packages
  tasks:
    - name: Backup all vms in the Proxmox cluster to storage mypbs
      community.general.proxmox_backup:
        api_user: "{{ api_user }}"
        api_password: "{{ api_secret }}"
        api_host: "{{ api_host }}"
        storage: "{{ backup_storage }}"
        mode: all
