---
- name: Install Apache web server
  become: true
  ansible.builtin.apt:
    name: lighttpd
    state: present
    update_cache: true

- name: Update Apache configuration
  ansible.builtin.lineinfile:
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^server.port                 = 80'
    line: 'server.port = 9090'

- name: Start Apache service
  become: true
  ansible.builtin.service:
    name: lighttpd
    state: started
