---
# 1. ignore_errors - Ignoring the error
- name: Copy index.html  with ignore_error
  ansible.builtin.template:
    src: index.html
    dest: /home/nextzen
    mode: '0755'
  register: copy_result
  ignore_errors: true

- name: String Variable from - main_playbook_variable
  ansible.builtin.debug:
    var: copy_result


# 2. any_errors_fatal
- name: Copy index.html  with failed_when
  ansible.builtin.template:
    src: index.html
    dest: /home/nextzen
    mode: '0755'
  # failed_when:
  #   - copy_result.failed == true
  # any_errors_fatal: true
  register: copy_result
  ignore_errors: true
#
#
- name: Create a file if it does not exist
  ansible.builtin.command: touch /home/nextzen/myfile.txt
  register: file_created
  changed_when: file_created.rc == 0
