---
- name: Import Lazydocker Tasks
  ansible.builtin.import_tasks: lazydocker.yml
###########################################################################
- name: Necessary Package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ apt_packages }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
############################################################################
- name: Initialize nextzen folder structure
  become: true
  ansible.builtin.copy:
    src: "{{ resource_base_dir }}/database"
    dest: "{{ install_dest }}"
    owner: "{{ default_owner }}"
    group: "{{ default_group }}"
    mode: '0644'
#################################
- name: Create groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items: "{{ database_groups }}"
################################
- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    state: present
  with_items: "{{ database_users }}"
#################################
- name: Configure directory permission
  ansible.builtin.file:
    path: "{{ install_dest }}/{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
    recurse: true
  with_items: "{{ directories }}"
