---
- name: Nextzen Automation Playbook
  hosts: all
  become: true
  remote_user: root
  tasks:
    - name: Install sshpass
      ansible.builtin.apt:
        name: sshpass
        state: present
        update_cache: true
    - name: Download script to /usr/bin
      ansible.builtin.get_url:
        url: "{{ zfs_snapshot_script }}"
        dest: "/usr/bin"
        mode: '0755'
    - name: Get input Value
      ansible.builtin.debug:
        msg: "Prepare to snapshot \nDataset: {{ dataset }} \nRetain: {{ retain }}"
    - name: Execute Snapshot
      ansible.builtin.command:
        cmd: >-
          ZFS-Snapshot {{ dataset }} {{ retain }}
      tags:
        - skip_ansible_lint
