---
- name: Nextzen Automation Playbook
  hosts: all
  become: true
  remote_user: root
  tasks:
    - name: Download script to /usr/bin
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/KaySar12/ansible-resources/refs/heads/main/ProxmoxVE/resources/scripts/ZFS-Snapshot"
        dest: "/usr/bin"
        mode: '0755'
    - name: Execute Snapshot
      ansible.builtin.command:
        cmd: >-
          ZFS-Snapshot {{ dataset }} {{ retain }}
      tags:
        - skip_ansible_lint
