---
- name: Example Ansible playbook
  hosts: all
  remote_user: root
  roles:
    - handlers
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: true
      become_user: root
