services:
    semaphore_db:
        image: mysql:8
        environment:
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
            MYSQL_DATABASE: ${MYSQL_DB:-semaphore}
            MYSQL_RANDOM_ROOT_PASSWORD: yes
        volumes:
            - ${MYSQL_DATA:-./semaphore_mysql}:/var/lib/mysql   
        networks:
            - semaphore_network
    semaphore:
        ports:
            - ${APP_PORT:-80}:3000
        image: semaphoreui/semaphore:v2.10.43
        environment:
            SEMAPHORE_DB_DIALECT: mysql
            SEMAPHORE_DB_HOST: semaphore_db
            SEMAPHORE_DB_NAME: ${MYSQL_DB:-semaphore}
            SEMAPHORE_DB_USER: ${MYSQL_USER:-user}
            SEMAPHORE_DB_PASS: ${MYSQL_PASSWORD:-password}
            SEMAPHORE_ADMIN: ${APP_USER:-admin}
            SEMAPHORE_ADMIN_PASSWORD: ${APP_PASSS:-password}
            SEMAPHORE_ADMIN_NAME: ${APP_NAME:-admin}
            SEMAPHORE_ADMIN_EMAIL: ${APP_MAIL:-admin@gmail.com}
        volumes:
            - ${APP_DATA:-./semaphore_data}:/var/lib/semaphore
            - ${APP_CONF:-./semaphore_config}:/etc/semaphore
            
        networks:
            - semaphore_network
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_mysql:
networks:
    semaphore_network: {driver: "bridge"}
