BASE_DIR=/root/dev/Ansible/ansible-resources/NextZen-Automation
RESOURCES=resources
INITIALIZE=1-initialize
nextzen-initialize:
	@ansible-playbook --inventory ${BASE_DIR}/${RESOURCES}/inventory/hosts.ini ${BASE_DIR}/${INITIALIZE}/initialize.yml