---
install_dest: /home/nextzen
database_dest: /home/nextzen/database
apps_dest: /home/nextzen/database/apps
default_owner: nextzen
default_group: nextzen
default_apps:
  - account_center
  - nextweb
  - nextdns
  - nextvpn
  - nextnas
  - nextzenos
  - nextfirewall
apt_packages:
  - acl
  - lsof
  - iputils-ping
  - htop
  - duf
  - python3-pexpect 
  - jq
tools:
  lazydocker: https://github.com/jesseduffield/lazydocker/releases/download/v0.24.1/lazydocker_0.24.1_Linux_x86_64.tar.gz