---
- name: Install Ansible (Debian/Ubuntu)
  ansible.builtin.apt:
    name: ansible
    state: present
    update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Initialize outpost folder
  become: true
  ansible.builtin.copy:
    src: "{{ resource_base_dir }}/docker/outpost"
    dest: "{{ database_dest }}"
    owner: "{{ default_owner }}"
    group: "{{ default_group }}"
    mode: '0755'
- name: Pull outpost image
  community.docker.docker_compose_v2_pull:
    project_src: "{{ database_dest }}/outpost"
- name: Start Outpost Service
  community.docker.docker_compose_v2:
    project_src: "{{ database_dest }}/outpost"
  register: output
- name: Show results
  ansible.builtin.debug:
    var: output
