---
- name: Install lighttpd web server
  become: true
  ansible.builtin.apt:
    name: lighttpd
    state: present
    update_cache: true

- name: Generate configuration file
  ansible.builtin.template:
    src: myconfig.j2
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: '0644'
  vars:
    server_port: 9090

- name: Start lighttpd service
  become: true
  ansible.builtin.service:
    name: lighttpd
    state: restarted
