---
- name: Example Ansible playbook for all kind of Variable
  hosts: all
  become: true
  remote_user: root
  roles:
    - custom-role

  vars:
    # 1. String Variable
    main_playbook_variable: "first varible in main playbook"

    # 2. Boolean Variable
    is_enabled: false

    # 3. List Variable
    fruits:
      - apple
      - banana
      - orange

    # 4. Dictionary Variable
    fruit_prices:
      apple: 0.5
      banana: 0.25
      orange: 0.75

    # 5. Referencing nested variable
    fruit_basket:
      - name: John
        fruits:
          - apple
          - orange
      - name: Jane
        fruits:
          - banana
          - apple
          - orange

  # 6. Variable from the my-vars.yml
  vars_files:
    - my-vars.yml

  tasks:
    - name: String Variable from - main_playbook_variable
      ansible.builtin.debug:
        var: main_playbook_variable

    - name: Boolean variable
      ansible.builtin.debug:
        msg: "Variable is true"
      when: is_enabled

    - name: List variable - Print list of fruits
      ansible.builtin.debug:
        var: fruits

    - name: List variable - Reference individual item in list
      ansible.builtin.debug:
        var: fruits[0]

    - name: Dictionary Variable - Accessing all dictionary variable
      ansible.builtin.debug:
        var: fruit_prices

    - name: Dictionary Variable - Accessing individual specific fields
      ansible.builtin.debug:
        var: fruit_prices.apple
    - name: Get the price of an apple
      ansible.builtin.command: echo "{{ fruit_prices['apple'] }}"
      register: apple_price_as_registered_var
      tags:
        - skip_ansible_lint
    - name: Print the value of register variable
      ansible.builtin.debug:
        var: apple_price_as_registered_var.stdout

    - name: Get the value of apple from the nested variable
      ansible.builtin.debug:
        var: fruit_prices[fruit_basket[0].fruits[0]]

    # Jinja 2 filter on variables
    - name: Using Jinja 2 filters on variables
      ansible.builtin.debug:
        var: fruit_prices.keys() | list | map('upper') | list

    # Accessing variable inside playbook from my-vars.yml
    - name: Get the value of variable from my-vars.yml
      ansible.builtin.debug:
        var: vars_from_my_vars_yml

    # Defining and accessing the variable at RunTime
    - name: Get the value from run time
      ansible.builtin.debug:
        var: version
    # Defining and accessing the variable at RunTime
    - name: Print the value of variable when var file is passed at run time
      ansible.builtin.debug:
        var: other_variable
    - name: Call to an API
      ansible.builtin.uri:
        url: https://ifconfig.nextzenos.com/ip
        method: GET
      register: results
    - name: Get API Result
      ansible.builtin.debug:
        var: results.json
